version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Installing source NPM dependencies
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the project...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
